### ISSUE TITLE
Test Failure

### ISSUE THREAD

**Issue by CelsoDeSa** [oshi-shinobu/ruby-espeak#1]
I'm getting these errors, but I think I'm missing some configuration, what would it be?
    
1) Error:
TestEspeak#test_save:
Errno::ENOENT: No such file or directory @ unlink_internal - test.wav
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:76:in `delete'
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:76:in `ensure in test_save'
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:76:in `test_save'

  2) Error:
TestEspeak#test_saves:
Errno::ENOENT: No such file or directory @ unlink_internal - test.wav
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:65:in `delete'
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:65:in `ensure in test_saves'
    /home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:65:in `test_saves'

  3) Failure:
TestEspeak#test_says [/home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:50]:
--- expected
+++ actual
@@ -1 +1,2 @@
-""
+" DIs_ Iz_ a#_ t'Est_
+"

  4) Failure:
TestEspeak#test_execute [/home/celso/workspace/speechtest/ruby-espeak/test/test_espeak.rb:44]:
--- expected
+++ actual
@@ -1 +1,2 @@
-""
+" DIs_ Iz_ a#_ t'Est_
+"

11 runs, 10 assertions, 2 failures, 2 errors, 0 skips
rake aborted!

**Comment by CelsoDeSa** [comment]
Ok I got it right.
